//! Generated by tools/gen-kso-policy. Do not edit by hand.

use super::graph::{KsoNode, KsoNodeRuntime};
use super::policy::{KsoCapability, KsoFailurePolicy, KsoNodeKind, KsoPolicy, KsoStartupFnId};
use super::state::KsoNodeId;

pub const AHCI: KsoNodeId = KsoNodeId(1);
pub const ARCHITECTURE: KsoNodeId = KsoNodeId(2);
pub const BLOCK_LAYER: KsoNodeId = KsoNodeId(3);
pub const BOOT_RUNTIME: KsoNodeId = KsoNodeId(4);
pub const BOOTINFO: KsoNodeId = KsoNodeId(5);
pub const FRAMEBUFFER: KsoNodeId = KsoNodeId(6);
pub const GDT: KsoNodeId = KsoNodeId(7);
pub const HEAP: KsoNodeId = KsoNodeId(8);
pub const I8042: KsoNodeId = KsoNodeId(9);
pub const IDLELOOP: KsoNodeId = KsoNodeId(10);
pub const IDT: KsoNodeId = KsoNodeId(11);
pub const INPUT: KsoNodeId = KsoNodeId(12);
pub const INTERRUPTS: KsoNodeId = KsoNodeId(13);
pub const KERNEL_CONSTRUCTED: KsoNodeId = KsoNodeId(14);
pub const KERNEL_MAIN: KsoNodeId = KsoNodeId(15);
pub const KERNEL_MAPPER: KsoNodeId = KsoNodeId(16);
pub const MEMORY_MAP: KsoNodeId = KsoNodeId(17);
pub const MTSS_PID0: KsoNodeId = KsoNodeId(18);
pub const NVME: KsoNodeId = KsoNodeId(19);
pub const PAGING: KsoNodeId = KsoNodeId(20);
pub const PCI: KsoNodeId = KsoNodeId(21);
pub const PHYSICAL_ALLOCATOR: KsoNodeId = KsoNodeId(22);
pub const PIC: KsoNodeId = KsoNodeId(23);
pub const PID1_HANDOFF: KsoNodeId = KsoNodeId(24);
pub const PS2_KEYBOARD: KsoNodeId = KsoNodeId(25);
pub const ROOTFS: KsoNodeId = KsoNodeId(26);
pub const SEED_RS: KsoNodeId = KsoNodeId(27);
pub const SERIAL: KsoNodeId = KsoNodeId(28);
pub const SUPERVISOR: KsoNodeId = KsoNodeId(29);
pub const USB_CORE: KsoNodeId = KsoNodeId(30);
pub const USB_HID: KsoNodeId = KsoNodeId(31);
pub const USB_KEYBOARD: KsoNodeId = KsoNodeId(32);
pub const USERSPACE_LOADER: KsoNodeId = KsoNodeId(33);
pub const XHCI: KsoNodeId = KsoNodeId(34);

const AHCI_AFTER: [KsoNodeId; 2] = [KsoNodeId(3), KsoNodeId(21)];
const AHCI_WANTS: [KsoNodeId; 0] = [];
const AHCI_REQUIRES: [KsoCapability; 2] = [KsoCapability("pci.bus"), KsoCapability("block.layer")];
const AHCI_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const AHCI_PROVIDES: [KsoCapability; 1] = [KsoCapability("storage.ahci")];
const AHCI_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const ARCHITECTURE_AFTER: [KsoNodeId; 1] = [KsoNodeId(15)];
const ARCHITECTURE_WANTS: [KsoNodeId; 0] = [];
const ARCHITECTURE_REQUIRES: [KsoCapability; 1] = [KsoCapability("kernel.main")];
const ARCHITECTURE_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const ARCHITECTURE_PROVIDES: [KsoCapability; 1] = [KsoCapability("arch.ready")];
const ARCHITECTURE_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const BLOCK_LAYER_AFTER: [KsoNodeId; 1] = [KsoNodeId(8)];
const BLOCK_LAYER_WANTS: [KsoNodeId; 0] = [];
const BLOCK_LAYER_REQUIRES: [KsoCapability; 1] = [KsoCapability("heap.ready")];
const BLOCK_LAYER_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const BLOCK_LAYER_PROVIDES: [KsoCapability; 1] = [KsoCapability("block.layer")];
const BLOCK_LAYER_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const BOOT_RUNTIME_AFTER: [KsoNodeId; 2] = [KsoNodeId(3), KsoNodeId(8)];
const BOOT_RUNTIME_WANTS: [KsoNodeId; 0] = [];
const BOOT_RUNTIME_REQUIRES: [KsoCapability; 2] =
    [KsoCapability("block.layer"), KsoCapability("heap.ready")];
const BOOT_RUNTIME_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const BOOT_RUNTIME_PROVIDES: [KsoCapability; 2] = [
    KsoCapability("boot.runtime.validated"),
    KsoCapability("boot.spider_rs_image"),
];
const BOOT_RUNTIME_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const BOOTINFO_AFTER: [KsoNodeId; 1] = [KsoNodeId(27)];
const BOOTINFO_WANTS: [KsoNodeId; 0] = [];
const BOOTINFO_REQUIRES: [KsoCapability; 1] = [KsoCapability("boot.seed")];
const BOOTINFO_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const BOOTINFO_PROVIDES: [KsoCapability; 1] = [KsoCapability("boot.info")];
const BOOTINFO_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const FRAMEBUFFER_AFTER: [KsoNodeId; 2] = [KsoNodeId(5), KsoNodeId(20)];
const FRAMEBUFFER_WANTS: [KsoNodeId; 0] = [];
const FRAMEBUFFER_REQUIRES: [KsoCapability; 2] =
    [KsoCapability("boot.info"), KsoCapability("paging.ready")];
const FRAMEBUFFER_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const FRAMEBUFFER_PROVIDES: [KsoCapability; 1] = [KsoCapability("framebuffer.ready")];
const FRAMEBUFFER_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const GDT_AFTER: [KsoNodeId; 1] = [KsoNodeId(2)];
const GDT_WANTS: [KsoNodeId; 0] = [];
const GDT_REQUIRES: [KsoCapability; 1] = [KsoCapability("arch.ready")];
const GDT_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const GDT_PROVIDES: [KsoCapability; 1] = [KsoCapability("gdt.ready")];
const GDT_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const HEAP_AFTER: [KsoNodeId; 1] = [KsoNodeId(20)];
const HEAP_WANTS: [KsoNodeId; 0] = [];
const HEAP_REQUIRES: [KsoCapability; 1] = [KsoCapability("paging.ready")];
const HEAP_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const HEAP_PROVIDES: [KsoCapability; 1] = [KsoCapability("heap.ready")];
const HEAP_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const I8042_AFTER: [KsoNodeId; 1] = [KsoNodeId(13)];
const I8042_WANTS: [KsoNodeId; 0] = [];
const I8042_REQUIRES: [KsoCapability; 1] = [KsoCapability("interrupts.ready")];
const I8042_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const I8042_PROVIDES: [KsoCapability; 1] = [KsoCapability("i8042.controller")];
const I8042_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const IDLELOOP_AFTER: [KsoNodeId; 1] = [KsoNodeId(24)];
const IDLELOOP_WANTS: [KsoNodeId; 0] = [];
const IDLELOOP_REQUIRES: [KsoCapability; 1] = [KsoCapability("pid1.handoff")];
const IDLELOOP_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const IDLELOOP_PROVIDES: [KsoCapability; 1] = [KsoCapability("idleloop.ready")];
const IDLELOOP_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const IDT_AFTER: [KsoNodeId; 1] = [KsoNodeId(7)];
const IDT_WANTS: [KsoNodeId; 0] = [];
const IDT_REQUIRES: [KsoCapability; 1] = [KsoCapability("gdt.ready")];
const IDT_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const IDT_PROVIDES: [KsoCapability; 1] = [KsoCapability("idt.ready")];
const IDT_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const INPUT_AFTER: [KsoNodeId; 2] = [KsoNodeId(25), KsoNodeId(32)];
const INPUT_WANTS: [KsoNodeId; 2] = [KsoNodeId(25), KsoNodeId(32)];
const INPUT_REQUIRES: [KsoCapability; 0] = [];
const INPUT_WANTS_CAPABILITIES: [KsoCapability; 2] = [
    KsoCapability("input.keyboard.ps2"),
    KsoCapability("input.keyboard.usb"),
];
const INPUT_PROVIDES: [KsoCapability; 1] = [KsoCapability("input.ready")];
const INPUT_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const INTERRUPTS_AFTER: [KsoNodeId; 2] = [KsoNodeId(11), KsoNodeId(23)];
const INTERRUPTS_WANTS: [KsoNodeId; 0] = [];
const INTERRUPTS_REQUIRES: [KsoCapability; 2] =
    [KsoCapability("pic.ready"), KsoCapability("idt.ready")];
const INTERRUPTS_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const INTERRUPTS_PROVIDES: [KsoCapability; 1] = [KsoCapability("interrupts.ready")];
const INTERRUPTS_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const KERNEL_CONSTRUCTED_AFTER: [KsoNodeId; 1] = [KsoNodeId(15)];
const KERNEL_CONSTRUCTED_WANTS: [KsoNodeId; 0] = [];
const KERNEL_CONSTRUCTED_REQUIRES: [KsoCapability; 1] = [KsoCapability("kernel.main")];
const KERNEL_CONSTRUCTED_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const KERNEL_CONSTRUCTED_PROVIDES: [KsoCapability; 1] = [KsoCapability("kernel.constructed")];
const KERNEL_CONSTRUCTED_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const KERNEL_MAIN_AFTER: [KsoNodeId; 1] = [KsoNodeId(5)];
const KERNEL_MAIN_WANTS: [KsoNodeId; 0] = [];
const KERNEL_MAIN_REQUIRES: [KsoCapability; 1] = [KsoCapability("boot.info")];
const KERNEL_MAIN_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const KERNEL_MAIN_PROVIDES: [KsoCapability; 1] = [KsoCapability("kernel.main")];
const KERNEL_MAIN_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const KERNEL_MAPPER_AFTER: [KsoNodeId; 1] = [KsoNodeId(22)];
const KERNEL_MAPPER_WANTS: [KsoNodeId; 0] = [];
const KERNEL_MAPPER_REQUIRES: [KsoCapability; 1] = [KsoCapability("memory.physical_allocator")];
const KERNEL_MAPPER_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const KERNEL_MAPPER_PROVIDES: [KsoCapability; 1] = [KsoCapability("memory.kernel_mapper")];
const KERNEL_MAPPER_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const MEMORY_MAP_AFTER: [KsoNodeId; 1] = [KsoNodeId(5)];
const MEMORY_MAP_WANTS: [KsoNodeId; 0] = [];
const MEMORY_MAP_REQUIRES: [KsoCapability; 1] = [KsoCapability("boot.info")];
const MEMORY_MAP_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const MEMORY_MAP_PROVIDES: [KsoCapability; 1] = [KsoCapability("memory.map")];
const MEMORY_MAP_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const MTSS_PID0_AFTER: [KsoNodeId; 2] = [KsoNodeId(8), KsoNodeId(29)];
const MTSS_PID0_WANTS: [KsoNodeId; 0] = [];
const MTSS_PID0_REQUIRES: [KsoCapability; 2] = [
    KsoCapability("supervisor.ready"),
    KsoCapability("heap.ready"),
];
const MTSS_PID0_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const MTSS_PID0_PROVIDES: [KsoCapability; 4] = [
    KsoCapability("mtss.pid0"),
    KsoCapability("mtss.core"),
    KsoCapability("mtss.scheduler"),
    KsoCapability("mtss.cooperative"),
];
const MTSS_PID0_OPTIONAL_PROVIDES: [KsoCapability; 2] = [
    KsoCapability("mtss.timer"),
    KsoCapability("mtss.preemption"),
];
const NVME_AFTER: [KsoNodeId; 2] = [KsoNodeId(3), KsoNodeId(21)];
const NVME_WANTS: [KsoNodeId; 0] = [];
const NVME_REQUIRES: [KsoCapability; 2] = [KsoCapability("pci.bus"), KsoCapability("block.layer")];
const NVME_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const NVME_PROVIDES: [KsoCapability; 1] = [KsoCapability("storage.nvme")];
const NVME_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const PAGING_AFTER: [KsoNodeId; 2] = [KsoNodeId(7), KsoNodeId(16)];
const PAGING_WANTS: [KsoNodeId; 0] = [];
const PAGING_REQUIRES: [KsoCapability; 2] = [
    KsoCapability("memory.kernel_mapper"),
    KsoCapability("gdt.ready"),
];
const PAGING_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const PAGING_PROVIDES: [KsoCapability; 1] = [KsoCapability("paging.ready")];
const PAGING_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const PCI_AFTER: [KsoNodeId; 2] = [KsoNodeId(13), KsoNodeId(20)];
const PCI_WANTS: [KsoNodeId; 0] = [];
const PCI_REQUIRES: [KsoCapability; 2] = [
    KsoCapability("paging.ready"),
    KsoCapability("interrupts.ready"),
];
const PCI_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const PCI_PROVIDES: [KsoCapability; 1] = [KsoCapability("pci.bus")];
const PCI_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const PHYSICAL_ALLOCATOR_AFTER: [KsoNodeId; 1] = [KsoNodeId(17)];
const PHYSICAL_ALLOCATOR_WANTS: [KsoNodeId; 0] = [];
const PHYSICAL_ALLOCATOR_REQUIRES: [KsoCapability; 1] = [KsoCapability("memory.map")];
const PHYSICAL_ALLOCATOR_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const PHYSICAL_ALLOCATOR_PROVIDES: [KsoCapability; 1] =
    [KsoCapability("memory.physical_allocator")];
const PHYSICAL_ALLOCATOR_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const PIC_AFTER: [KsoNodeId; 1] = [KsoNodeId(11)];
const PIC_WANTS: [KsoNodeId; 0] = [];
const PIC_REQUIRES: [KsoCapability; 1] = [KsoCapability("idt.ready")];
const PIC_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const PIC_PROVIDES: [KsoCapability; 1] = [KsoCapability("pic.ready")];
const PIC_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const PID1_HANDOFF_AFTER: [KsoNodeId; 3] = [KsoNodeId(18), KsoNodeId(29), KsoNodeId(33)];
const PID1_HANDOFF_WANTS: [KsoNodeId; 1] = [KsoNodeId(18)];
const PID1_HANDOFF_REQUIRES: [KsoCapability; 5] = [
    KsoCapability("boot.spider_rs_image"),
    KsoCapability("supervisor.launch_grants"),
    KsoCapability("mtss.pid0"),
    KsoCapability("mtss.scheduler"),
    KsoCapability("userspace.loader"),
];
const PID1_HANDOFF_WANTS_CAPABILITIES: [KsoCapability; 1] = [KsoCapability("mtss.preemption")];
const PID1_HANDOFF_PROVIDES: [KsoCapability; 1] = [KsoCapability("pid1.handoff")];
const PID1_HANDOFF_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const PS2_KEYBOARD_AFTER: [KsoNodeId; 1] = [KsoNodeId(9)];
const PS2_KEYBOARD_WANTS: [KsoNodeId; 0] = [];
const PS2_KEYBOARD_REQUIRES: [KsoCapability; 0] = [];
const PS2_KEYBOARD_WANTS_CAPABILITIES: [KsoCapability; 1] = [KsoCapability("i8042.controller")];
const PS2_KEYBOARD_PROVIDES: [KsoCapability; 1] = [KsoCapability("input.keyboard.ps2")];
const PS2_KEYBOARD_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const ROOTFS_AFTER: [KsoNodeId; 1] = [KsoNodeId(4)];
const ROOTFS_WANTS: [KsoNodeId; 0] = [];
const ROOTFS_REQUIRES: [KsoCapability; 1] = [KsoCapability("boot.runtime.validated")];
const ROOTFS_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const ROOTFS_PROVIDES: [KsoCapability; 1] = [KsoCapability("rootfs.mounted")];
const ROOTFS_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const SEED_RS_AFTER: [KsoNodeId; 0] = [];
const SEED_RS_WANTS: [KsoNodeId; 0] = [];
const SEED_RS_REQUIRES: [KsoCapability; 0] = [];
const SEED_RS_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const SEED_RS_PROVIDES: [KsoCapability; 1] = [KsoCapability("boot.seed")];
const SEED_RS_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const SERIAL_AFTER: [KsoNodeId; 1] = [KsoNodeId(2)];
const SERIAL_WANTS: [KsoNodeId; 0] = [];
const SERIAL_REQUIRES: [KsoCapability; 1] = [KsoCapability("arch.ready")];
const SERIAL_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const SERIAL_PROVIDES: [KsoCapability; 1] = [KsoCapability("serial.console")];
const SERIAL_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const SUPERVISOR_AFTER: [KsoNodeId; 2] = [KsoNodeId(13), KsoNodeId(26)];
const SUPERVISOR_WANTS: [KsoNodeId; 0] = [];
const SUPERVISOR_REQUIRES: [KsoCapability; 2] = [
    KsoCapability("rootfs.mounted"),
    KsoCapability("interrupts.ready"),
];
const SUPERVISOR_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const SUPERVISOR_PROVIDES: [KsoCapability; 2] = [
    KsoCapability("supervisor.ready"),
    KsoCapability("supervisor.launch_grants"),
];
const SUPERVISOR_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const USB_CORE_AFTER: [KsoNodeId; 1] = [KsoNodeId(34)];
const USB_CORE_WANTS: [KsoNodeId; 1] = [KsoNodeId(31)];
const USB_CORE_REQUIRES: [KsoCapability; 0] = [];
const USB_CORE_WANTS_CAPABILITIES: [KsoCapability; 1] = [KsoCapability("usb.xhci")];
const USB_CORE_PROVIDES: [KsoCapability; 1] = [KsoCapability("usb.core")];
const USB_CORE_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const USB_HID_AFTER: [KsoNodeId; 1] = [KsoNodeId(30)];
const USB_HID_WANTS: [KsoNodeId; 0] = [];
const USB_HID_REQUIRES: [KsoCapability; 0] = [];
const USB_HID_WANTS_CAPABILITIES: [KsoCapability; 1] = [KsoCapability("usb.core")];
const USB_HID_PROVIDES: [KsoCapability; 1] = [KsoCapability("usb.hid")];
const USB_HID_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const USB_KEYBOARD_AFTER: [KsoNodeId; 1] = [KsoNodeId(31)];
const USB_KEYBOARD_WANTS: [KsoNodeId; 0] = [];
const USB_KEYBOARD_REQUIRES: [KsoCapability; 0] = [];
const USB_KEYBOARD_WANTS_CAPABILITIES: [KsoCapability; 1] = [KsoCapability("usb.hid")];
const USB_KEYBOARD_PROVIDES: [KsoCapability; 1] = [KsoCapability("input.keyboard.usb")];
const USB_KEYBOARD_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const USERSPACE_LOADER_AFTER: [KsoNodeId; 2] = [KsoNodeId(18), KsoNodeId(26)];
const USERSPACE_LOADER_WANTS: [KsoNodeId; 0] = [];
const USERSPACE_LOADER_REQUIRES: [KsoCapability; 4] = [
    KsoCapability("mtss.pid0"),
    KsoCapability("mtss.core"),
    KsoCapability("mtss.scheduler"),
    KsoCapability("rootfs.mounted"),
];
const USERSPACE_LOADER_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const USERSPACE_LOADER_PROVIDES: [KsoCapability; 1] = [KsoCapability("userspace.loader")];
const USERSPACE_LOADER_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
const XHCI_AFTER: [KsoNodeId; 2] = [KsoNodeId(13), KsoNodeId(21)];
const XHCI_WANTS: [KsoNodeId; 0] = [];
const XHCI_REQUIRES: [KsoCapability; 2] =
    [KsoCapability("pci.bus"), KsoCapability("interrupts.ready")];
const XHCI_WANTS_CAPABILITIES: [KsoCapability; 0] = [];
const XHCI_PROVIDES: [KsoCapability; 1] = [KsoCapability("usb.xhci")];
const XHCI_OPTIONAL_PROVIDES: [KsoCapability; 0] = [];
pub static KSO_NODES: &[KsoNode] = &[
    KsoNode {
        id: AHCI,
        name: "AHCI",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(19),
        after: &AHCI_AFTER,
        wants: &AHCI_WANTS,
        requires: &AHCI_REQUIRES,
        wants_capabilities: &AHCI_WANTS_CAPABILITIES,
        provides: &AHCI_PROVIDES,
        optional_provides: &AHCI_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: ARCHITECTURE,
        name: "Architecture",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(5),
        after: &ARCHITECTURE_AFTER,
        wants: &ARCHITECTURE_WANTS,
        requires: &ARCHITECTURE_REQUIRES,
        wants_capabilities: &ARCHITECTURE_WANTS_CAPABILITIES,
        provides: &ARCHITECTURE_PROVIDES,
        optional_provides: &ARCHITECTURE_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: BLOCK_LAYER,
        name: "Block Layer",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(18),
        after: &BLOCK_LAYER_AFTER,
        wants: &BLOCK_LAYER_WANTS,
        requires: &BLOCK_LAYER_REQUIRES,
        wants_capabilities: &BLOCK_LAYER_WANTS_CAPABILITIES,
        provides: &BLOCK_LAYER_PROVIDES,
        optional_provides: &BLOCK_LAYER_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: BOOT_RUNTIME,
        name: "Boot Runtime Validator",
        kind: KsoNodeKind::SupervisorService,
        startup: KsoStartupFnId(28),
        after: &BOOT_RUNTIME_AFTER,
        wants: &BOOT_RUNTIME_WANTS,
        requires: &BOOT_RUNTIME_REQUIRES,
        wants_capabilities: &BOOT_RUNTIME_WANTS_CAPABILITIES,
        provides: &BOOT_RUNTIME_PROVIDES,
        optional_provides: &BOOT_RUNTIME_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: BOOTINFO,
        name: "BootInfo",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(2),
        after: &BOOTINFO_AFTER,
        wants: &BOOTINFO_WANTS,
        requires: &BOOTINFO_REQUIRES,
        wants_capabilities: &BOOTINFO_WANTS_CAPABILITIES,
        provides: &BOOTINFO_PROVIDES,
        optional_provides: &BOOTINFO_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: FRAMEBUFFER,
        name: "Framebuffer",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(13),
        after: &FRAMEBUFFER_AFTER,
        wants: &FRAMEBUFFER_WANTS,
        requires: &FRAMEBUFFER_REQUIRES,
        wants_capabilities: &FRAMEBUFFER_WANTS_CAPABILITIES,
        provides: &FRAMEBUFFER_PROVIDES,
        optional_provides: &FRAMEBUFFER_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: GDT,
        name: "GDT",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(7),
        after: &GDT_AFTER,
        wants: &GDT_WANTS,
        requires: &GDT_REQUIRES,
        wants_capabilities: &GDT_WANTS_CAPABILITIES,
        provides: &GDT_PROVIDES,
        optional_provides: &GDT_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: HEAP,
        name: "Kernel Heap",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(12),
        after: &HEAP_AFTER,
        wants: &HEAP_WANTS,
        requires: &HEAP_REQUIRES,
        wants_capabilities: &HEAP_WANTS_CAPABILITIES,
        provides: &HEAP_PROVIDES,
        optional_provides: &HEAP_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: I8042,
        name: "i8042 Controller",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(21),
        after: &I8042_AFTER,
        wants: &I8042_WANTS,
        requires: &I8042_REQUIRES,
        wants_capabilities: &I8042_WANTS_CAPABILITIES,
        provides: &I8042_PROVIDES,
        optional_provides: &I8042_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: IDLELOOP,
        name: "Idle Loop",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(34),
        after: &IDLELOOP_AFTER,
        wants: &IDLELOOP_WANTS,
        requires: &IDLELOOP_REQUIRES,
        wants_capabilities: &IDLELOOP_WANTS_CAPABILITIES,
        provides: &IDLELOOP_PROVIDES,
        optional_provides: &IDLELOOP_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: IDT,
        name: "IDT",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(14),
        after: &IDT_AFTER,
        wants: &IDT_WANTS,
        requires: &IDT_REQUIRES,
        wants_capabilities: &IDT_WANTS_CAPABILITIES,
        provides: &IDT_PROVIDES,
        optional_provides: &IDT_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: INPUT,
        name: "Input Subsystem",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(27),
        after: &INPUT_AFTER,
        wants: &INPUT_WANTS,
        requires: &INPUT_REQUIRES,
        wants_capabilities: &INPUT_WANTS_CAPABILITIES,
        provides: &INPUT_PROVIDES,
        optional_provides: &INPUT_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: INTERRUPTS,
        name: "Interrupts",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(16),
        after: &INTERRUPTS_AFTER,
        wants: &INTERRUPTS_WANTS,
        requires: &INTERRUPTS_REQUIRES,
        wants_capabilities: &INTERRUPTS_WANTS_CAPABILITIES,
        provides: &INTERRUPTS_PROVIDES,
        optional_provides: &INTERRUPTS_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: KERNEL_CONSTRUCTED,
        name: "Kernel Constructed",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(4),
        after: &KERNEL_CONSTRUCTED_AFTER,
        wants: &KERNEL_CONSTRUCTED_WANTS,
        requires: &KERNEL_CONSTRUCTED_REQUIRES,
        wants_capabilities: &KERNEL_CONSTRUCTED_WANTS_CAPABILITIES,
        provides: &KERNEL_CONSTRUCTED_PROVIDES,
        optional_provides: &KERNEL_CONSTRUCTED_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: KERNEL_MAIN,
        name: "Kernel Main",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(3),
        after: &KERNEL_MAIN_AFTER,
        wants: &KERNEL_MAIN_WANTS,
        requires: &KERNEL_MAIN_REQUIRES,
        wants_capabilities: &KERNEL_MAIN_WANTS_CAPABILITIES,
        provides: &KERNEL_MAIN_PROVIDES,
        optional_provides: &KERNEL_MAIN_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: KERNEL_MAPPER,
        name: "Kernel Mapper",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(10),
        after: &KERNEL_MAPPER_AFTER,
        wants: &KERNEL_MAPPER_WANTS,
        requires: &KERNEL_MAPPER_REQUIRES,
        wants_capabilities: &KERNEL_MAPPER_WANTS_CAPABILITIES,
        provides: &KERNEL_MAPPER_PROVIDES,
        optional_provides: &KERNEL_MAPPER_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: MEMORY_MAP,
        name: "Memory Map",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(8),
        after: &MEMORY_MAP_AFTER,
        wants: &MEMORY_MAP_WANTS,
        requires: &MEMORY_MAP_REQUIRES,
        wants_capabilities: &MEMORY_MAP_WANTS_CAPABILITIES,
        provides: &MEMORY_MAP_PROVIDES,
        optional_provides: &MEMORY_MAP_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: MTSS_PID0,
        name: "MTSS PID0",
        kind: KsoNodeKind::MtssMechanism,
        startup: KsoStartupFnId(31),
        after: &MTSS_PID0_AFTER,
        wants: &MTSS_PID0_WANTS,
        requires: &MTSS_PID0_REQUIRES,
        wants_capabilities: &MTSS_PID0_WANTS_CAPABILITIES,
        provides: &MTSS_PID0_PROVIDES,
        optional_provides: &MTSS_PID0_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: NVME,
        name: "NVMe",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(20),
        after: &NVME_AFTER,
        wants: &NVME_WANTS,
        requires: &NVME_REQUIRES,
        wants_capabilities: &NVME_WANTS_CAPABILITIES,
        provides: &NVME_PROVIDES,
        optional_provides: &NVME_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: PAGING,
        name: "Paging",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(11),
        after: &PAGING_AFTER,
        wants: &PAGING_WANTS,
        requires: &PAGING_REQUIRES,
        wants_capabilities: &PAGING_WANTS_CAPABILITIES,
        provides: &PAGING_PROVIDES,
        optional_provides: &PAGING_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: PCI,
        name: "PCI",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(17),
        after: &PCI_AFTER,
        wants: &PCI_WANTS,
        requires: &PCI_REQUIRES,
        wants_capabilities: &PCI_WANTS_CAPABILITIES,
        provides: &PCI_PROVIDES,
        optional_provides: &PCI_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: PHYSICAL_ALLOCATOR,
        name: "Physical Allocator",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(9),
        after: &PHYSICAL_ALLOCATOR_AFTER,
        wants: &PHYSICAL_ALLOCATOR_WANTS,
        requires: &PHYSICAL_ALLOCATOR_REQUIRES,
        wants_capabilities: &PHYSICAL_ALLOCATOR_WANTS_CAPABILITIES,
        provides: &PHYSICAL_ALLOCATOR_PROVIDES,
        optional_provides: &PHYSICAL_ALLOCATOR_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: PIC,
        name: "PIC",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(15),
        after: &PIC_AFTER,
        wants: &PIC_WANTS,
        requires: &PIC_REQUIRES,
        wants_capabilities: &PIC_WANTS_CAPABILITIES,
        provides: &PIC_PROVIDES,
        optional_provides: &PIC_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: PID1_HANDOFF,
        name: "PID1 Handoff",
        kind: KsoNodeKind::UserspaceBootstrap,
        startup: KsoStartupFnId(33),
        after: &PID1_HANDOFF_AFTER,
        wants: &PID1_HANDOFF_WANTS,
        requires: &PID1_HANDOFF_REQUIRES,
        wants_capabilities: &PID1_HANDOFF_WANTS_CAPABILITIES,
        provides: &PID1_HANDOFF_PROVIDES,
        optional_provides: &PID1_HANDOFF_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: true,
            require_preemption: false,
        },
    },
    KsoNode {
        id: PS2_KEYBOARD,
        name: "PS/2 Keyboard",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(22),
        after: &PS2_KEYBOARD_AFTER,
        wants: &PS2_KEYBOARD_WANTS,
        requires: &PS2_KEYBOARD_REQUIRES,
        wants_capabilities: &PS2_KEYBOARD_WANTS_CAPABILITIES,
        provides: &PS2_KEYBOARD_PROVIDES,
        optional_provides: &PS2_KEYBOARD_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: ROOTFS,
        name: "Root Filesystem",
        kind: KsoNodeKind::SupervisorService,
        startup: KsoStartupFnId(29),
        after: &ROOTFS_AFTER,
        wants: &ROOTFS_WANTS,
        requires: &ROOTFS_REQUIRES,
        wants_capabilities: &ROOTFS_WANTS_CAPABILITIES,
        provides: &ROOTFS_PROVIDES,
        optional_provides: &ROOTFS_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: SEED_RS,
        name: "Seed RS",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(1),
        after: &SEED_RS_AFTER,
        wants: &SEED_RS_WANTS,
        requires: &SEED_RS_REQUIRES,
        wants_capabilities: &SEED_RS_WANTS_CAPABILITIES,
        provides: &SEED_RS_PROVIDES,
        optional_provides: &SEED_RS_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: SERIAL,
        name: "Serial Console",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(6),
        after: &SERIAL_AFTER,
        wants: &SERIAL_WANTS,
        requires: &SERIAL_REQUIRES,
        wants_capabilities: &SERIAL_WANTS_CAPABILITIES,
        provides: &SERIAL_PROVIDES,
        optional_provides: &SERIAL_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: SUPERVISOR,
        name: "Mirage Supervisor",
        kind: KsoNodeKind::SupervisorService,
        startup: KsoStartupFnId(30),
        after: &SUPERVISOR_AFTER,
        wants: &SUPERVISOR_WANTS,
        requires: &SUPERVISOR_REQUIRES,
        wants_capabilities: &SUPERVISOR_WANTS_CAPABILITIES,
        provides: &SUPERVISOR_PROVIDES,
        optional_provides: &SUPERVISOR_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: USB_CORE,
        name: "USB Core",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(24),
        after: &USB_CORE_AFTER,
        wants: &USB_CORE_WANTS,
        requires: &USB_CORE_REQUIRES,
        wants_capabilities: &USB_CORE_WANTS_CAPABILITIES,
        provides: &USB_CORE_PROVIDES,
        optional_provides: &USB_CORE_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: USB_HID,
        name: "USB HID",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(25),
        after: &USB_HID_AFTER,
        wants: &USB_HID_WANTS,
        requires: &USB_HID_REQUIRES,
        wants_capabilities: &USB_HID_WANTS_CAPABILITIES,
        provides: &USB_HID_PROVIDES,
        optional_provides: &USB_HID_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: USB_KEYBOARD,
        name: "USB Keyboard",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(26),
        after: &USB_KEYBOARD_AFTER,
        wants: &USB_KEYBOARD_WANTS,
        requires: &USB_KEYBOARD_REQUIRES,
        wants_capabilities: &USB_KEYBOARD_WANTS_CAPABILITIES,
        provides: &USB_KEYBOARD_PROVIDES,
        optional_provides: &USB_KEYBOARD_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: USERSPACE_LOADER,
        name: "Userspace Loader",
        kind: KsoNodeKind::UserspaceBootstrap,
        startup: KsoStartupFnId(32),
        after: &USERSPACE_LOADER_AFTER,
        wants: &USERSPACE_LOADER_WANTS,
        requires: &USERSPACE_LOADER_REQUIRES,
        wants_capabilities: &USERSPACE_LOADER_WANTS_CAPABILITIES,
        provides: &USERSPACE_LOADER_PROVIDES,
        optional_provides: &USERSPACE_LOADER_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
    KsoNode {
        id: XHCI,
        name: "xHCI",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(23),
        after: &XHCI_AFTER,
        wants: &XHCI_WANTS,
        requires: &XHCI_REQUIRES,
        wants_capabilities: &XHCI_WANTS_CAPABILITIES,
        provides: &XHCI_PROVIDES,
        optional_provides: &XHCI_OPTIONAL_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
            allow_cooperative_mtss: false,
            require_preemption: false,
        },
    },
];
pub const KSO_RUNTIME_INIT: KsoNodeRuntime = KsoNodeRuntime::new();
