//! Generated by tools/gen-kso-policy. Do not edit by hand.

use super::graph::{KsoNode, KsoNodeRuntime};
use super::policy::{KsoCapability, KsoFailurePolicy, KsoNodeKind, KsoPolicy, KsoStartupFnId};
use super::state::KsoNodeId;

pub const AHCI: KsoNodeId = KsoNodeId(1);
pub const ARCHITECTURE: KsoNodeId = KsoNodeId(2);
pub const BLOCK_LAYER: KsoNodeId = KsoNodeId(3);
pub const BOOT_RUNTIME: KsoNodeId = KsoNodeId(4);
pub const BOOTINFO: KsoNodeId = KsoNodeId(5);
pub const FRAMEBUFFER: KsoNodeId = KsoNodeId(6);
pub const GDT: KsoNodeId = KsoNodeId(7);
pub const HEAP: KsoNodeId = KsoNodeId(8);
pub const I8042: KsoNodeId = KsoNodeId(9);
pub const IDLELOOP: KsoNodeId = KsoNodeId(10);
pub const IDT: KsoNodeId = KsoNodeId(11);
pub const INTERRUPTS: KsoNodeId = KsoNodeId(12);
pub const KERNEL_MAIN: KsoNodeId = KsoNodeId(13);
pub const KERNEL_MAPPER: KsoNodeId = KsoNodeId(14);
pub const MEMORY_MAP: KsoNodeId = KsoNodeId(15);
pub const MTSS_PID0: KsoNodeId = KsoNodeId(16);
pub const NVME: KsoNodeId = KsoNodeId(17);
pub const PAGING: KsoNodeId = KsoNodeId(18);
pub const PCI: KsoNodeId = KsoNodeId(19);
pub const PHYSICAL_ALLOCATOR: KsoNodeId = KsoNodeId(20);
pub const PIC: KsoNodeId = KsoNodeId(21);
pub const PID1_HANDOFF: KsoNodeId = KsoNodeId(22);
pub const PS2_KEYBOARD: KsoNodeId = KsoNodeId(23);
pub const ROOTFS: KsoNodeId = KsoNodeId(24);
pub const SEED_RS: KsoNodeId = KsoNodeId(25);
pub const SERIAL: KsoNodeId = KsoNodeId(26);
pub const SUPERVISOR: KsoNodeId = KsoNodeId(27);
pub const USB_CORE: KsoNodeId = KsoNodeId(28);
pub const USERSPACE_LOADER: KsoNodeId = KsoNodeId(29);
pub const XHCI: KsoNodeId = KsoNodeId(30);

const AHCI_AFTER: [KsoNodeId; 2] = [KsoNodeId(3), KsoNodeId(19)];
const AHCI_WANTS: [KsoNodeId; 0] = [];
const AHCI_REQUIRES: [KsoCapability; 2] = [KsoCapability("pci.bus"), KsoCapability("block.layer")];
const AHCI_PROVIDES: [KsoCapability; 1] = [KsoCapability("storage.ahci")];
const ARCHITECTURE_AFTER: [KsoNodeId; 1] = [KsoNodeId(13)];
const ARCHITECTURE_WANTS: [KsoNodeId; 0] = [];
const ARCHITECTURE_REQUIRES: [KsoCapability; 1] = [KsoCapability("kernel.main")];
const ARCHITECTURE_PROVIDES: [KsoCapability; 1] = [KsoCapability("arch.ready")];
const BLOCK_LAYER_AFTER: [KsoNodeId; 1] = [KsoNodeId(8)];
const BLOCK_LAYER_WANTS: [KsoNodeId; 0] = [];
const BLOCK_LAYER_REQUIRES: [KsoCapability; 1] = [KsoCapability("heap.ready")];
const BLOCK_LAYER_PROVIDES: [KsoCapability; 1] = [KsoCapability("block.layer")];
const BOOT_RUNTIME_AFTER: [KsoNodeId; 2] = [KsoNodeId(3), KsoNodeId(8)];
const BOOT_RUNTIME_WANTS: [KsoNodeId; 0] = [];
const BOOT_RUNTIME_REQUIRES: [KsoCapability; 2] =
    [KsoCapability("block.layer"), KsoCapability("heap.ready")];
const BOOT_RUNTIME_PROVIDES: [KsoCapability; 1] = [KsoCapability("boot.runtime.validated")];
const BOOTINFO_AFTER: [KsoNodeId; 1] = [KsoNodeId(25)];
const BOOTINFO_WANTS: [KsoNodeId; 0] = [];
const BOOTINFO_REQUIRES: [KsoCapability; 1] = [KsoCapability("boot.seed")];
const BOOTINFO_PROVIDES: [KsoCapability; 1] = [KsoCapability("boot.info")];
const FRAMEBUFFER_AFTER: [KsoNodeId; 2] = [KsoNodeId(5), KsoNodeId(18)];
const FRAMEBUFFER_WANTS: [KsoNodeId; 0] = [];
const FRAMEBUFFER_REQUIRES: [KsoCapability; 2] =
    [KsoCapability("boot.info"), KsoCapability("paging.ready")];
const FRAMEBUFFER_PROVIDES: [KsoCapability; 1] = [KsoCapability("framebuffer.ready")];
const GDT_AFTER: [KsoNodeId; 1] = [KsoNodeId(2)];
const GDT_WANTS: [KsoNodeId; 0] = [];
const GDT_REQUIRES: [KsoCapability; 1] = [KsoCapability("arch.ready")];
const GDT_PROVIDES: [KsoCapability; 1] = [KsoCapability("gdt.ready")];
const HEAP_AFTER: [KsoNodeId; 1] = [KsoNodeId(18)];
const HEAP_WANTS: [KsoNodeId; 0] = [];
const HEAP_REQUIRES: [KsoCapability; 1] = [KsoCapability("paging.ready")];
const HEAP_PROVIDES: [KsoCapability; 1] = [KsoCapability("heap.ready")];
const I8042_AFTER: [KsoNodeId; 1] = [KsoNodeId(12)];
const I8042_WANTS: [KsoNodeId; 0] = [];
const I8042_REQUIRES: [KsoCapability; 1] = [KsoCapability("interrupts.ready")];
const I8042_PROVIDES: [KsoCapability; 1] = [KsoCapability("i8042.controller")];
const IDLELOOP_AFTER: [KsoNodeId; 1] = [KsoNodeId(22)];
const IDLELOOP_WANTS: [KsoNodeId; 0] = [];
const IDLELOOP_REQUIRES: [KsoCapability; 1] = [KsoCapability("pid1.handoff")];
const IDLELOOP_PROVIDES: [KsoCapability; 1] = [KsoCapability("idleloop.ready")];
const IDT_AFTER: [KsoNodeId; 1] = [KsoNodeId(7)];
const IDT_WANTS: [KsoNodeId; 0] = [];
const IDT_REQUIRES: [KsoCapability; 1] = [KsoCapability("gdt.ready")];
const IDT_PROVIDES: [KsoCapability; 1] = [KsoCapability("idt.ready")];
const INTERRUPTS_AFTER: [KsoNodeId; 2] = [KsoNodeId(11), KsoNodeId(21)];
const INTERRUPTS_WANTS: [KsoNodeId; 0] = [];
const INTERRUPTS_REQUIRES: [KsoCapability; 2] =
    [KsoCapability("pic.ready"), KsoCapability("idt.ready")];
const INTERRUPTS_PROVIDES: [KsoCapability; 1] = [KsoCapability("interrupts.ready")];
const KERNEL_MAIN_AFTER: [KsoNodeId; 1] = [KsoNodeId(5)];
const KERNEL_MAIN_WANTS: [KsoNodeId; 0] = [];
const KERNEL_MAIN_REQUIRES: [KsoCapability; 1] = [KsoCapability("boot.info")];
const KERNEL_MAIN_PROVIDES: [KsoCapability; 1] = [KsoCapability("kernel.main")];
const KERNEL_MAPPER_AFTER: [KsoNodeId; 1] = [KsoNodeId(20)];
const KERNEL_MAPPER_WANTS: [KsoNodeId; 0] = [];
const KERNEL_MAPPER_REQUIRES: [KsoCapability; 1] = [KsoCapability("memory.physical_allocator")];
const KERNEL_MAPPER_PROVIDES: [KsoCapability; 1] = [KsoCapability("memory.kernel_mapper")];
const MEMORY_MAP_AFTER: [KsoNodeId; 1] = [KsoNodeId(5)];
const MEMORY_MAP_WANTS: [KsoNodeId; 0] = [];
const MEMORY_MAP_REQUIRES: [KsoCapability; 1] = [KsoCapability("boot.info")];
const MEMORY_MAP_PROVIDES: [KsoCapability; 1] = [KsoCapability("memory.map")];
const MTSS_PID0_AFTER: [KsoNodeId; 2] = [KsoNodeId(8), KsoNodeId(27)];
const MTSS_PID0_WANTS: [KsoNodeId; 0] = [];
const MTSS_PID0_REQUIRES: [KsoCapability; 2] = [
    KsoCapability("supervisor.ready"),
    KsoCapability("heap.ready"),
];
const MTSS_PID0_PROVIDES: [KsoCapability; 1] = [KsoCapability("mtss.pid0")];
const NVME_AFTER: [KsoNodeId; 2] = [KsoNodeId(3), KsoNodeId(19)];
const NVME_WANTS: [KsoNodeId; 0] = [];
const NVME_REQUIRES: [KsoCapability; 2] = [KsoCapability("pci.bus"), KsoCapability("block.layer")];
const NVME_PROVIDES: [KsoCapability; 1] = [KsoCapability("storage.nvme")];
const PAGING_AFTER: [KsoNodeId; 2] = [KsoNodeId(7), KsoNodeId(14)];
const PAGING_WANTS: [KsoNodeId; 0] = [];
const PAGING_REQUIRES: [KsoCapability; 2] = [
    KsoCapability("memory.kernel_mapper"),
    KsoCapability("gdt.ready"),
];
const PAGING_PROVIDES: [KsoCapability; 1] = [KsoCapability("paging.ready")];
const PCI_AFTER: [KsoNodeId; 2] = [KsoNodeId(12), KsoNodeId(18)];
const PCI_WANTS: [KsoNodeId; 0] = [];
const PCI_REQUIRES: [KsoCapability; 2] = [
    KsoCapability("paging.ready"),
    KsoCapability("interrupts.ready"),
];
const PCI_PROVIDES: [KsoCapability; 1] = [KsoCapability("pci.bus")];
const PHYSICAL_ALLOCATOR_AFTER: [KsoNodeId; 1] = [KsoNodeId(15)];
const PHYSICAL_ALLOCATOR_WANTS: [KsoNodeId; 0] = [];
const PHYSICAL_ALLOCATOR_REQUIRES: [KsoCapability; 1] = [KsoCapability("memory.map")];
const PHYSICAL_ALLOCATOR_PROVIDES: [KsoCapability; 1] =
    [KsoCapability("memory.physical_allocator")];
const PIC_AFTER: [KsoNodeId; 1] = [KsoNodeId(11)];
const PIC_WANTS: [KsoNodeId; 0] = [];
const PIC_REQUIRES: [KsoCapability; 1] = [KsoCapability("idt.ready")];
const PIC_PROVIDES: [KsoCapability; 1] = [KsoCapability("pic.ready")];
const PID1_HANDOFF_AFTER: [KsoNodeId; 2] = [KsoNodeId(27), KsoNodeId(29)];
const PID1_HANDOFF_WANTS: [KsoNodeId; 0] = [];
const PID1_HANDOFF_REQUIRES: [KsoCapability; 2] = [
    KsoCapability("userspace.loader"),
    KsoCapability("supervisor.ready"),
];
const PID1_HANDOFF_PROVIDES: [KsoCapability; 1] = [KsoCapability("pid1.handoff")];
const PS2_KEYBOARD_AFTER: [KsoNodeId; 1] = [KsoNodeId(9)];
const PS2_KEYBOARD_WANTS: [KsoNodeId; 0] = [];
const PS2_KEYBOARD_REQUIRES: [KsoCapability; 1] = [KsoCapability("i8042.controller")];
const PS2_KEYBOARD_PROVIDES: [KsoCapability; 1] = [KsoCapability("input.keyboard.ps2")];
const ROOTFS_AFTER: [KsoNodeId; 1] = [KsoNodeId(4)];
const ROOTFS_WANTS: [KsoNodeId; 0] = [];
const ROOTFS_REQUIRES: [KsoCapability; 1] = [KsoCapability("boot.runtime.validated")];
const ROOTFS_PROVIDES: [KsoCapability; 1] = [KsoCapability("rootfs.mounted")];
const SEED_RS_AFTER: [KsoNodeId; 0] = [];
const SEED_RS_WANTS: [KsoNodeId; 0] = [];
const SEED_RS_REQUIRES: [KsoCapability; 0] = [];
const SEED_RS_PROVIDES: [KsoCapability; 1] = [KsoCapability("boot.seed")];
const SERIAL_AFTER: [KsoNodeId; 1] = [KsoNodeId(2)];
const SERIAL_WANTS: [KsoNodeId; 0] = [];
const SERIAL_REQUIRES: [KsoCapability; 1] = [KsoCapability("arch.ready")];
const SERIAL_PROVIDES: [KsoCapability; 1] = [KsoCapability("serial.console")];
const SUPERVISOR_AFTER: [KsoNodeId; 2] = [KsoNodeId(12), KsoNodeId(24)];
const SUPERVISOR_WANTS: [KsoNodeId; 0] = [];
const SUPERVISOR_REQUIRES: [KsoCapability; 2] = [
    KsoCapability("rootfs.mounted"),
    KsoCapability("interrupts.ready"),
];
const SUPERVISOR_PROVIDES: [KsoCapability; 1] = [KsoCapability("supervisor.ready")];
const USB_CORE_AFTER: [KsoNodeId; 1] = [KsoNodeId(30)];
const USB_CORE_WANTS: [KsoNodeId; 0] = [];
const USB_CORE_REQUIRES: [KsoCapability; 1] = [KsoCapability("usb.xhci")];
const USB_CORE_PROVIDES: [KsoCapability; 1] = [KsoCapability("usb.core")];
const USERSPACE_LOADER_AFTER: [KsoNodeId; 2] = [KsoNodeId(16), KsoNodeId(24)];
const USERSPACE_LOADER_WANTS: [KsoNodeId; 0] = [];
const USERSPACE_LOADER_REQUIRES: [KsoCapability; 2] =
    [KsoCapability("mtss.pid0"), KsoCapability("rootfs.mounted")];
const USERSPACE_LOADER_PROVIDES: [KsoCapability; 1] = [KsoCapability("userspace.loader")];
const XHCI_AFTER: [KsoNodeId; 2] = [KsoNodeId(12), KsoNodeId(19)];
const XHCI_WANTS: [KsoNodeId; 0] = [];
const XHCI_REQUIRES: [KsoCapability; 2] =
    [KsoCapability("pci.bus"), KsoCapability("interrupts.ready")];
const XHCI_PROVIDES: [KsoCapability; 1] = [KsoCapability("usb.xhci")];
pub static KSO_NODES: &[KsoNode] = &[
    KsoNode {
        id: AHCI,
        name: "AHCI",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(18),
        after: &AHCI_AFTER,
        wants: &AHCI_WANTS,
        requires: &AHCI_REQUIRES,
        provides: &AHCI_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
        },
    },
    KsoNode {
        id: ARCHITECTURE,
        name: "Architecture",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(4),
        after: &ARCHITECTURE_AFTER,
        wants: &ARCHITECTURE_WANTS,
        requires: &ARCHITECTURE_REQUIRES,
        provides: &ARCHITECTURE_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: BLOCK_LAYER,
        name: "Block Layer",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(17),
        after: &BLOCK_LAYER_AFTER,
        wants: &BLOCK_LAYER_WANTS,
        requires: &BLOCK_LAYER_REQUIRES,
        provides: &BLOCK_LAYER_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: BOOT_RUNTIME,
        name: "Boot Runtime Validator",
        kind: KsoNodeKind::SupervisorService,
        startup: KsoStartupFnId(24),
        after: &BOOT_RUNTIME_AFTER,
        wants: &BOOT_RUNTIME_WANTS,
        requires: &BOOT_RUNTIME_REQUIRES,
        provides: &BOOT_RUNTIME_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: BOOTINFO,
        name: "BootInfo",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(2),
        after: &BOOTINFO_AFTER,
        wants: &BOOTINFO_WANTS,
        requires: &BOOTINFO_REQUIRES,
        provides: &BOOTINFO_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: FRAMEBUFFER,
        name: "Framebuffer",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(12),
        after: &FRAMEBUFFER_AFTER,
        wants: &FRAMEBUFFER_WANTS,
        requires: &FRAMEBUFFER_REQUIRES,
        provides: &FRAMEBUFFER_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
        },
    },
    KsoNode {
        id: GDT,
        name: "GDT",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(6),
        after: &GDT_AFTER,
        wants: &GDT_WANTS,
        requires: &GDT_REQUIRES,
        provides: &GDT_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: HEAP,
        name: "Kernel Heap",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(11),
        after: &HEAP_AFTER,
        wants: &HEAP_WANTS,
        requires: &HEAP_REQUIRES,
        provides: &HEAP_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: I8042,
        name: "i8042 Controller",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(20),
        after: &I8042_AFTER,
        wants: &I8042_WANTS,
        requires: &I8042_REQUIRES,
        provides: &I8042_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
        },
    },
    KsoNode {
        id: IDLELOOP,
        name: "Idle Loop",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(30),
        after: &IDLELOOP_AFTER,
        wants: &IDLELOOP_WANTS,
        requires: &IDLELOOP_REQUIRES,
        provides: &IDLELOOP_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: IDT,
        name: "IDT",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(13),
        after: &IDT_AFTER,
        wants: &IDT_WANTS,
        requires: &IDT_REQUIRES,
        provides: &IDT_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: INTERRUPTS,
        name: "Interrupts",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(15),
        after: &INTERRUPTS_AFTER,
        wants: &INTERRUPTS_WANTS,
        requires: &INTERRUPTS_REQUIRES,
        provides: &INTERRUPTS_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: KERNEL_MAIN,
        name: "Kernel Main",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(3),
        after: &KERNEL_MAIN_AFTER,
        wants: &KERNEL_MAIN_WANTS,
        requires: &KERNEL_MAIN_REQUIRES,
        provides: &KERNEL_MAIN_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: KERNEL_MAPPER,
        name: "Kernel Mapper",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(9),
        after: &KERNEL_MAPPER_AFTER,
        wants: &KERNEL_MAPPER_WANTS,
        requires: &KERNEL_MAPPER_REQUIRES,
        provides: &KERNEL_MAPPER_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: MEMORY_MAP,
        name: "Memory Map",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(7),
        after: &MEMORY_MAP_AFTER,
        wants: &MEMORY_MAP_WANTS,
        requires: &MEMORY_MAP_REQUIRES,
        provides: &MEMORY_MAP_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: MTSS_PID0,
        name: "MTSS PID0",
        kind: KsoNodeKind::MtssMechanism,
        startup: KsoStartupFnId(27),
        after: &MTSS_PID0_AFTER,
        wants: &MTSS_PID0_WANTS,
        requires: &MTSS_PID0_REQUIRES,
        provides: &MTSS_PID0_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: NVME,
        name: "NVMe",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(19),
        after: &NVME_AFTER,
        wants: &NVME_WANTS,
        requires: &NVME_REQUIRES,
        provides: &NVME_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
        },
    },
    KsoNode {
        id: PAGING,
        name: "Paging",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(10),
        after: &PAGING_AFTER,
        wants: &PAGING_WANTS,
        requires: &PAGING_REQUIRES,
        provides: &PAGING_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: PCI,
        name: "PCI",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(16),
        after: &PCI_AFTER,
        wants: &PCI_WANTS,
        requires: &PCI_REQUIRES,
        provides: &PCI_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
        },
    },
    KsoNode {
        id: PHYSICAL_ALLOCATOR,
        name: "Physical Allocator",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(8),
        after: &PHYSICAL_ALLOCATOR_AFTER,
        wants: &PHYSICAL_ALLOCATOR_WANTS,
        requires: &PHYSICAL_ALLOCATOR_REQUIRES,
        provides: &PHYSICAL_ALLOCATOR_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: PIC,
        name: "PIC",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(14),
        after: &PIC_AFTER,
        wants: &PIC_WANTS,
        requires: &PIC_REQUIRES,
        provides: &PIC_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: PID1_HANDOFF,
        name: "PID1 Handoff",
        kind: KsoNodeKind::UserspaceBootstrap,
        startup: KsoStartupFnId(29),
        after: &PID1_HANDOFF_AFTER,
        wants: &PID1_HANDOFF_WANTS,
        requires: &PID1_HANDOFF_REQUIRES,
        provides: &PID1_HANDOFF_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: PS2_KEYBOARD,
        name: "PS/2 Keyboard",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(21),
        after: &PS2_KEYBOARD_AFTER,
        wants: &PS2_KEYBOARD_WANTS,
        requires: &PS2_KEYBOARD_REQUIRES,
        provides: &PS2_KEYBOARD_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
        },
    },
    KsoNode {
        id: ROOTFS,
        name: "Root Filesystem",
        kind: KsoNodeKind::SupervisorService,
        startup: KsoStartupFnId(25),
        after: &ROOTFS_AFTER,
        wants: &ROOTFS_WANTS,
        requires: &ROOTFS_REQUIRES,
        provides: &ROOTFS_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: SEED_RS,
        name: "Seed RS",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(1),
        after: &SEED_RS_AFTER,
        wants: &SEED_RS_WANTS,
        requires: &SEED_RS_REQUIRES,
        provides: &SEED_RS_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: SERIAL,
        name: "Serial Console",
        kind: KsoNodeKind::KernelMechanism,
        startup: KsoStartupFnId(5),
        after: &SERIAL_AFTER,
        wants: &SERIAL_WANTS,
        requires: &SERIAL_REQUIRES,
        provides: &SERIAL_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: SUPERVISOR,
        name: "Mirage Supervisor",
        kind: KsoNodeKind::SupervisorService,
        startup: KsoStartupFnId(26),
        after: &SUPERVISOR_AFTER,
        wants: &SUPERVISOR_WANTS,
        requires: &SUPERVISOR_REQUIRES,
        provides: &SUPERVISOR_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: USB_CORE,
        name: "USB Core",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(23),
        after: &USB_CORE_AFTER,
        wants: &USB_CORE_WANTS,
        requires: &USB_CORE_REQUIRES,
        provides: &USB_CORE_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
        },
    },
    KsoNode {
        id: USERSPACE_LOADER,
        name: "Userspace Loader",
        kind: KsoNodeKind::UserspaceBootstrap,
        startup: KsoStartupFnId(28),
        after: &USERSPACE_LOADER_AFTER,
        wants: &USERSPACE_LOADER_WANTS,
        requires: &USERSPACE_LOADER_REQUIRES,
        provides: &USERSPACE_LOADER_PROVIDES,
        policy: KsoPolicy {
            required: true,
            allow_missing_wants: false,
            failure: KsoFailurePolicy::Fatal,
        },
    },
    KsoNode {
        id: XHCI,
        name: "xHCI",
        kind: KsoNodeKind::DriverService,
        startup: KsoStartupFnId(22),
        after: &XHCI_AFTER,
        wants: &XHCI_WANTS,
        requires: &XHCI_REQUIRES,
        provides: &XHCI_PROVIDES,
        policy: KsoPolicy {
            required: false,
            allow_missing_wants: true,
            failure: KsoFailurePolicy::AllowDegraded,
        },
    },
];
pub const KSO_RUNTIME_INIT: KsoNodeRuntime = KsoNodeRuntime::new();
