//! Generated by gen-device-db. Do not edit by hand.
#![allow(dead_code)]

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct InputDeviceDescriptor { pub kind: &'static str, pub name: &'static str, pub driver_hints: &'static [&'static str] }
const INPUT_DEVICE_DESCRIPTORS: &[InputDeviceDescriptor] = &[
    InputDeviceDescriptor { kind: "i8042-controller", name: "Intel 8042-compatible PS/2 Controller", driver_hints: &["i8042", "inputd"] },
    InputDeviceDescriptor { kind: "ps2-keyboard", name: "PS/2 Keyboard", driver_hints: &["ps2-keyboard", "inputd"] },
    InputDeviceDescriptor { kind: "usb-hid-keyboard", name: "USB HID Keyboard", driver_hints: &["xhci", "usbd", "hid", "inputd"] },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BlockDeviceDescriptor { pub kind: &'static str, pub name: &'static str, pub driver_hint: &'static str, pub default_block_size: u32 }
const BLOCK_DEVICE_DESCRIPTORS: &[BlockDeviceDescriptor] = &[
    BlockDeviceDescriptor { kind: "ahci-disk", name: "AHCI SATA Disk", driver_hint: "ahci/storaged", default_block_size: 512 },
    BlockDeviceDescriptor { kind: "atapi", name: "ATAPI Optical Media", driver_hint: "ahci-atapi/storaged", default_block_size: 2048 },
    BlockDeviceDescriptor { kind: "nvme", name: "NVMe Namespace", driver_hint: "nvme/storaged", default_block_size: 512 },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CharDeviceDescriptor { pub kind: &'static str, pub name: &'static str, pub driver_hints: &'static [&'static str] }
const CHAR_DEVICE_DESCRIPTORS: &[CharDeviceDescriptor] = &[
    CharDeviceDescriptor { kind: "entropy", name: "Entropy Source", driver_hints: &["rngd"] },
    CharDeviceDescriptor { kind: "framebuffer-console", name: "Framebuffer Console", driver_hints: &["fb", "console"] },
    CharDeviceDescriptor { kind: "null", name: "Null Character Device", driver_hints: &["devfs"] },
    CharDeviceDescriptor { kind: "serial-console", name: "16550-Compatible Serial Console", driver_hints: &["uart16550", "console"] },
    CharDeviceDescriptor { kind: "virtio-console", name: "VirtIO Console Port", driver_hints: &["virtio-console", "console"] },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PciVendorDescriptor { pub id: u16, pub name: &'static str, pub aliases: &'static [&'static str] }
const PCI_VENDOR_DESCRIPTORS: &[PciVendorDescriptor] = &[
    PciVendorDescriptor { id: 0x1002, name: "AMD", aliases: &["ATI Technologies"] },
    PciVendorDescriptor { id: 0x1022, name: "AMD", aliases: &["Advanced Micro Devices"] },
    PciVendorDescriptor { id: 0x1234, name: "QEMU", aliases: &["QEMU Project"] },
    PciVendorDescriptor { id: 0x1af4, name: "VirtIO", aliases: &["Red Hat VirtIO"] },
    PciVendorDescriptor { id: 0x8086, name: "Intel", aliases: &["Intel Corporation"] },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PciDeviceDescriptor { pub vendor_id: u16, pub device_id: u16, pub name: &'static str, pub driver_hint: Option<&'static str> }
const PCI_DEVICE_DESCRIPTORS: &[PciDeviceDescriptor] = &[
    PciDeviceDescriptor { vendor_id: 0x1002, device_id: 0x1636, name: "AMD Radeon Renoir Graphics", driver_hint: Some("amdgpu/displayd") },
    PciDeviceDescriptor { vendor_id: 0x1002, device_id: 0x1638, name: "AMD Radeon Renoir Graphics", driver_hint: Some("amdgpu/displayd") },
    PciDeviceDescriptor { vendor_id: 0x1022, device_id: 0x15e0, name: "AMD Renoir Root Complex", driver_hint: Some("amd-chipset/platformd") },
    PciDeviceDescriptor { vendor_id: 0x1022, device_id: 0x15e5, name: "AMD Renoir USB 3.1 xHCI Controller", driver_hint: Some("xhci/usbd") },
    PciDeviceDescriptor { vendor_id: 0x1234, device_id: 0x1111, name: "QEMU VGA Display Controller", driver_hint: Some("displayd") },
    PciDeviceDescriptor { vendor_id: 0x1af4, device_id: 0x1000, name: "VirtIO Network Device", driver_hint: Some("virtio-net/netd") },
    PciDeviceDescriptor { vendor_id: 0x1af4, device_id: 0x1001, name: "VirtIO Block Device", driver_hint: Some("virtio-blk/storaged") },
    PciDeviceDescriptor { vendor_id: 0x1af4, device_id: 0x1002, name: "VirtIO Memory Balloon", driver_hint: Some("virtio-balloon") },
    PciDeviceDescriptor { vendor_id: 0x1af4, device_id: 0x1003, name: "VirtIO Console", driver_hint: Some("virtio-console/console") },
    PciDeviceDescriptor { vendor_id: 0x1af4, device_id: 0x1004, name: "VirtIO SCSI Host", driver_hint: Some("virtio-scsi/storaged") },
    PciDeviceDescriptor { vendor_id: 0x1af4, device_id: 0x1005, name: "VirtIO RNG", driver_hint: Some("virtio-rng") },
    PciDeviceDescriptor { vendor_id: 0x1af4, device_id: 0x1009, name: "VirtIO 9P Transport", driver_hint: Some("virtio-9p/fsd") },
    PciDeviceDescriptor { vendor_id: 0x1af4, device_id: 0x1050, name: "VirtIO GPU", driver_hint: Some("virtio-gpu/displayd") },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x100e, name: "Intel 82540EM Gigabit Ethernet Controller", driver_hint: Some("e1000/netd") },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x10d3, name: "Intel 82574L Gigabit Network Connection", driver_hint: Some("e1000e/netd") },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x1237, name: "Intel 440FX Host Bridge", driver_hint: None },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x2415, name: "Intel 82801AA AC'97 Audio Controller", driver_hint: Some("ac97/audiod") },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x2668, name: "Intel ICH6 HD Audio Controller", driver_hint: Some("hda/audiod") },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x2918, name: "Intel ICH9 LPC Interface Controller", driver_hint: None },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x2922, name: "Intel ICH9 AHCI Controller", driver_hint: Some("ahci/storaged") },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x2934, name: "Intel ICH9 USB UHCI Controller", driver_hint: Some("uhci/usbd") },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x293a, name: "Intel ICH9 USB2 EHCI Controller", driver_hint: Some("ehci/usbd") },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x29c0, name: "Intel Q35 Host Bridge", driver_hint: None },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x7000, name: "Intel 82371SB PIIX3 ISA Bridge", driver_hint: None },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x7010, name: "Intel 82371SB PIIX3 IDE Interface", driver_hint: Some("ata/storaged") },
    PciDeviceDescriptor { vendor_id: 0x8086, device_id: 0x7113, name: "Intel 82371AB/EB/MB PIIX4 ACPI Bridge", driver_hint: None },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PciClassDescriptor { pub class: u8, pub subclass: Option<u8>, pub prog_if: Option<u8>, pub name: &'static str, pub driver_hint: Option<&'static str> }
const PCI_CLASS_DESCRIPTORS: &[PciClassDescriptor] = &[
    PciClassDescriptor { class: 0x01, subclass: Some(0x01), prog_if: Some(0x8a), name: "IDE Controller", driver_hint: Some("ata/storaged") },
    PciClassDescriptor { class: 0x01, subclass: Some(0x06), prog_if: Some(0x01), name: "AHCI Controller", driver_hint: Some("ahci/storaged") },
    PciClassDescriptor { class: 0x01, subclass: Some(0x08), prog_if: Some(0x02), name: "NVMe Controller", driver_hint: Some("nvme/storaged") },
    PciClassDescriptor { class: 0x02, subclass: Some(0x00), prog_if: None, name: "Ethernet Controller", driver_hint: Some("netd") },
    PciClassDescriptor { class: 0x03, subclass: Some(0x00), prog_if: None, name: "VGA Display Controller", driver_hint: Some("displayd") },
    PciClassDescriptor { class: 0x03, subclass: Some(0x80), prog_if: None, name: "Display Controller", driver_hint: Some("displayd") },
    PciClassDescriptor { class: 0x06, subclass: Some(0x00), prog_if: None, name: "Host Bridge", driver_hint: None },
    PciClassDescriptor { class: 0x06, subclass: Some(0x01), prog_if: None, name: "ISA Bridge", driver_hint: None },
    PciClassDescriptor { class: 0x06, subclass: Some(0x04), prog_if: None, name: "PCI-to-PCI Bridge", driver_hint: None },
    PciClassDescriptor { class: 0x0c, subclass: Some(0x03), prog_if: Some(0x20), name: "EHCI USB Controller", driver_hint: Some("ehci/usbd") },
    PciClassDescriptor { class: 0x0c, subclass: Some(0x03), prog_if: Some(0x30), name: "xHCI Controller", driver_hint: Some("xhci/usbd") },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UsbVendorDescriptor { pub id: u16, pub name: &'static str, pub aliases: &'static [&'static str] }
const USB_VENDOR_DESCRIPTORS: &[UsbVendorDescriptor] = &[
    UsbVendorDescriptor { id: 0x046d, name: "Logitech", aliases: &[] },
    UsbVendorDescriptor { id: 0x0627, name: "QEMU", aliases: &[] },
    UsbVendorDescriptor { id: 0x1d6b, name: "Linux Foundation", aliases: &[] },
    UsbVendorDescriptor { id: 0x8087, name: "Intel", aliases: &[] },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UsbDeviceDescriptor { pub vendor_id: u16, pub product_id: u16, pub name: &'static str, pub driver_hint: Option<&'static str> }
const USB_DEVICE_DESCRIPTORS: &[UsbDeviceDescriptor] = &[
    UsbDeviceDescriptor { vendor_id: 0x046d, product_id: 0xc077, name: "Logitech USB Optical Mouse", driver_hint: Some("hid/inputd") },
    UsbDeviceDescriptor { vendor_id: 0x046d, product_id: 0xc31c, name: "Logitech Keyboard K120", driver_hint: Some("hid/inputd") },
    UsbDeviceDescriptor { vendor_id: 0x0627, product_id: 0x0001, name: "QEMU USB Tablet", driver_hint: Some("hid/inputd") },
    UsbDeviceDescriptor { vendor_id: 0x1d6b, product_id: 0x0002, name: "USB 2.0 Root Hub", driver_hint: Some("usbhub/usbd") },
    UsbDeviceDescriptor { vendor_id: 0x1d6b, product_id: 0x0003, name: "USB 3.0 Root Hub", driver_hint: Some("usbhub/usbd") },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UsbClassDescriptor { pub class: u8, pub subclass: Option<u8>, pub prog_if: Option<u8>, pub name: &'static str, pub driver_hint: Option<&'static str> }
const USB_CLASS_DESCRIPTORS: &[UsbClassDescriptor] = &[
    UsbClassDescriptor { class: 0x03, subclass: None, prog_if: None, name: "Human Interface Device", driver_hint: Some("hid/inputd") },
    UsbClassDescriptor { class: 0x08, subclass: None, prog_if: None, name: "Mass Storage", driver_hint: Some("usb-storage/storaged") },
    UsbClassDescriptor { class: 0x09, subclass: None, prog_if: None, name: "Hub", driver_hint: Some("usbhub/usbd") },
    UsbClassDescriptor { class: 0x0a, subclass: None, prog_if: None, name: "CDC Data", driver_hint: Some("cdc/netd") },
    UsbClassDescriptor { class: 0xe0, subclass: Some(0x01), prog_if: Some(0x01), name: "Bluetooth Wireless Controller", driver_hint: Some("bluetoothd") },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ChipsetDescriptor { pub family: &'static str, pub name: &'static str, pub components: &'static [&'static str], pub driver_hints: &'static [&'static str] }
const CHIPSET_DESCRIPTORS: &[ChipsetDescriptor] = &[
    ChipsetDescriptor { family: "440FX", name: "Intel 440FX/PIIX3 QEMU PC Chipset", components: &["host-bridge", "isa-bridge", "ide", "acpi"], driver_hints: &["pci", "ata/storaged", "acpi"] },
    ChipsetDescriptor { family: "Promontory", name: "AMD 300/400/500-Series Chipset", components: &["pcie-root", "sata", "usb"], driver_hints: &["amd-chipset/platformd", "ahci/storaged", "xhci/usbd"] },
    ChipsetDescriptor { family: "Q35", name: "Intel Q35/ICH9 QEMU PC Chipset", components: &["host-bridge", "lpc", "ahci", "ehci", "uhci", "hda"], driver_hints: &["pci", "ahci/storaged", "ehci/usbd", "uhci/usbd", "hda/audiod"] },
    ChipsetDescriptor { family: "Renoir", name: "AMD Ryzen 4000 Mobile SoC", components: &["root-complex", "iommu", "xhci", "sata", "gpu"], driver_hints: &["amd-chipset/platformd", "amd-iommu", "xhci/usbd", "amdgpu/displayd"] },
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CpuInfo { pub family: u16, pub model: Option<u16>, pub stepping: Option<u8>, pub name: &'static str, pub codename: Option<&'static str>, pub driver_hints: &'static [&'static str], pub diagnostic_name: &'static str }
const AMD_CPU_INFOS: &[CpuInfo] = &[
    CpuInfo { family: 0x17, model: None, stepping: None, name: "AMD Zen/Zen+ CPU", codename: Some("Zen family 17h"), driver_hints: &["amd64", "ryzen"], diagnostic_name: "AMD Zen/Zen+ CPU (Zen family 17h); hints: amd64, ryzen" },
    CpuInfo { family: 0x17, model: Some(0x60), stepping: None, name: "AMD Ryzen 4000 Mobile APU", codename: Some("Renoir"), driver_hints: &["amd/renoir", "amdgpu/displayd", "xhci/usbd"], diagnostic_name: "AMD Ryzen 4000 Mobile APU (Renoir); hints: amd/renoir, amdgpu/displayd, xhci/usbd" },
    CpuInfo { family: 0x17, model: Some(0x60), stepping: Some(0x01), name: "AMD Ryzen 5 4500U", codename: Some("Renoir"), driver_hints: &["amd/renoir", "amdgpu/displayd", "xhci/usbd"], diagnostic_name: "AMD Ryzen 5 4500U (Renoir); hints: amd/renoir, amdgpu/displayd, xhci/usbd" },
    CpuInfo { family: 0x19, model: None, stepping: None, name: "AMD Zen 3/Zen 4 CPU", codename: Some("Zen family 19h"), driver_hints: &["amd64", "ryzen"], diagnostic_name: "AMD Zen 3/Zen 4 CPU (Zen family 19h); hints: amd64, ryzen" },
];
const INTEL_CPU_INFOS: &[CpuInfo] = &[
    CpuInfo { family: 0x06, model: None, stepping: None, name: "Intel 64 CPU", codename: Some("Family 6"), driver_hints: &["intel64"], diagnostic_name: "Intel 64 CPU (Family 6); hints: intel64" },
    CpuInfo { family: 0x06, model: Some(0x3c), stepping: None, name: "Intel Core 4th Gen CPU", codename: Some("Haswell"), driver_hints: &["intel64"], diagnostic_name: "Intel Core 4th Gen CPU (Haswell); hints: intel64" },
    CpuInfo { family: 0x06, model: Some(0x4e), stepping: None, name: "Intel Core 6th Gen Mobile CPU", codename: Some("Skylake-U/Y"), driver_hints: &["intel64"], diagnostic_name: "Intel Core 6th Gen Mobile CPU (Skylake-U/Y); hints: intel64" },
    CpuInfo { family: 0x06, model: Some(0x55), stepping: None, name: "Intel Xeon Scalable CPU", codename: Some("Skylake-SP/Cascade Lake-SP"), driver_hints: &["intel64"], diagnostic_name: "Intel Xeon Scalable CPU (Skylake-SP/Cascade Lake-SP); hints: intel64" },
    CpuInfo { family: 0x06, model: Some(0x6a), stepping: None, name: "Intel Xeon Scalable CPU", codename: Some("Ice Lake-SP"), driver_hints: &["intel64"], diagnostic_name: "Intel Xeon Scalable CPU (Ice Lake-SP); hints: intel64" },
];
const fn lookup_cpu(table: &'static [CpuInfo], family: u16, model: u16, stepping: u8) -> Option<&'static CpuInfo> { let mut mf=None; let mut ff=None; let mut i=0; while i<table.len(){ let e=&table[i]; if e.family==family { match (e.model,e.stepping){ (Some(m),Some(s)) if m==model && s==stepping => return Some(e), (Some(m),None) if m==model && mf.is_none()=>mf=Some(e), (None,None) if ff.is_none()=>ff=Some(e), _=>{} } } i+=1;} match mf { Some(e)=>Some(e), None=>ff } }
pub const fn lookup_cpu_amd(family:u16, model:u16, stepping:u8)->Option<&'static CpuInfo>{lookup_cpu(AMD_CPU_INFOS,family,model,stepping)}
pub const fn lookup_cpu_intel(family:u16, model:u16, stepping:u8)->Option<&'static CpuInfo>{lookup_cpu(INTEL_CPU_INFOS,family,model,stepping)}
pub fn lookup_block_kind(kind:&str)->Option<&'static BlockDeviceDescriptor>{BLOCK_DEVICE_DESCRIPTORS.iter().find(|e|e.kind==kind)}
pub fn lookup_input_kind(kind:&str)->Option<&'static InputDeviceDescriptor>{INPUT_DEVICE_DESCRIPTORS.iter().find(|e|e.kind==kind)}
