[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-mirage]
rustflags = [
    "-C", "link-arg=-Tlinker/x86_64.ld",
    "-C", "link-arg=--gc-sections",
    "-C", "link-arg=--no-eh-frame-hdr",
]

[alias]
kernel = "build --bin mirage-kernel --target targets/x86_64-mirage.json"
kernel-release = "build --release --bin mirage-kernel --target targets/x86_64-mirage.json"
