use std::{fs, path::Path};

fn write_valid(root: &Path) {
    for d in ["cpu", "pci", "usb", "block", "input", "char", "chipset"] {
        fs::create_dir_all(root.join(d)).unwrap();
    }
    fs::write(
        root.join("cpu/amd.toml"),
        r#"[[cpu]]
vendor="AuthenticAMD"
family=0x17
name="AMD CPU"
"#,
    )
    .unwrap();
    fs::write(
        root.join("pci/vendors.toml"),
        r#"[[vendor]]
id=0x1234
name="QEMU"
"#,
    )
    .unwrap();
    fs::write(
        root.join("pci/devices.toml"),
        r#"[[device]]
vendor_id=0x1234
device_id=0x1111
name="VGA"
"#,
    )
    .unwrap();
    fs::write(
        root.join("pci/classes.toml"),
        r#"[[class]]
class=0x03
subclass=0x00
name="Display"
"#,
    )
    .unwrap();
    fs::write(
        root.join("usb/vendors.toml"),
        r#"[[vendor]]
id=0x0627
name="QEMU"
"#,
    )
    .unwrap();
    fs::write(
        root.join("usb/devices.toml"),
        r#"[[device]]
vendor_id=0x0627
product_id=0x0001
name="Tablet"
"#,
    )
    .unwrap();
    fs::write(
        root.join("usb/classes.toml"),
        r#"[[class]]
class=0x03
name="HID"
"#,
    )
    .unwrap();
    fs::write(
        root.join("block/classes.toml"),
        r#"[[block]]
kind="nvme"
name="NVMe"
driver_hint="nvme/storaged"
default_block_size=512
"#,
    )
    .unwrap();
    fs::write(
        root.join("input/classes.toml"),
        r#"[[input]]
kind="keyboard"
name="Keyboard"
driver_hints=["inputd"]
"#,
    )
    .unwrap();
    fs::write(
        root.join("char/classes.toml"),
        r#"[[char]]
kind="console"
name="Console"
"#,
    )
    .unwrap();
    fs::write(
        root.join("chipset/amd.toml"),
        r#"[[chipset]]
family="Q35"
name="Chipset"
"#,
    )
    .unwrap();
    fs::write(
        root.join("aliases.toml"),
        r#"[aliases.cpu]
qemu64="cpu/amd:AuthenticAMD:0x17"
[aliases.pci]
vga="pci:0x1234:0x1111"
[aliases.usb]
tablet="usb:0x0627:0x0001"
hid="usb-class:0x03"
[aliases.block]
namespace="block:nvme"
[aliases.input]
kbd="input:keyboard"
[aliases.char]
con="char:console"
"#,
    )
    .unwrap();
}

#[test]
fn valid_parse() {
    let t = tempfile::tempdir().unwrap();
    write_valid(t.path());
    assert!(gen_device_db::load_database(t.path()).is_ok());
}
#[test]
fn invalid_hex_ids_fail() {
    let t = tempfile::tempdir().unwrap();
    write_valid(t.path());
    fs::write(
        t.path().join("pci/vendors.toml"),
        "[[vendor]]\nid=0x123\nname=\"bad\"\n",
    )
    .unwrap();
    assert!(gen_device_db::load_database(t.path())
        .unwrap_err()
        .contains("exactly 4"));
}
#[test]
fn duplicate_pci_usb_entries_fail() {
    let t = tempfile::tempdir().unwrap();
    write_valid(t.path());
    fs::write(t.path().join("usb/devices.toml"), "[[device]]\nvendor_id=0x0627\nproduct_id=0x0001\nname=\"a\"\n[[device]]\nvendor_id=0x0627\nproduct_id=0x0001\nname=\"b\"\n").unwrap();
    assert!(gen_device_db::load_database(t.path())
        .unwrap_err()
        .contains("duplicate USB device"));
}
#[test]
fn class_hierarchy_failures() {
    let t = tempfile::tempdir().unwrap();
    write_valid(t.path());
    fs::write(
        t.path().join("pci/classes.toml"),
        "[[class]]\nclass=0x01\nprog_if=0x01\nname=\"bad\"\n",
    )
    .unwrap();
    assert!(gen_device_db::load_database(t.path())
        .unwrap_err()
        .contains("prog_if requires subclass"));
}
#[test]
fn alias_failures() {
    let t = tempfile::tempdir().unwrap();
    write_valid(t.path());
    fs::write(
        t.path().join("aliases.toml"),
        "[aliases.pci]\nbad=\"pci:0x1234:0xffff\"\n",
    )
    .unwrap();
    assert!(gen_device_db::load_database(t.path())
        .unwrap_err()
        .contains("missing PCI"));
}
#[test]
fn output_is_deterministic() {
    let t = tempfile::tempdir().unwrap();
    write_valid(t.path());
    let db1 = gen_device_db::load_database(t.path()).unwrap();
    let a = gen_device_db::generate(&db1);
    let db2 = gen_device_db::load_database(t.path()).unwrap();
    let b = gen_device_db::generate(&db2);
    assert_eq!(a, b);
    assert!(a.contains("Generated by gen-device-db"));
}
