timeout: 0
default_entry: 1
graphics: yes
verbose: yes

/Mirage
    protocol: limine
    path: boot():/boot/mirage-kernel
    cmdline: mirage.boot=qemu mirage.console=serial,fb
    resolution: 1024x768x32
    kaslr: no
    module_path: boot():/spider-rt.img
    module_cmdline: mirage.module=spider-rt
