TIMEOUT=0
DEFAULT_ENTRY=1
GRAPHICS=yes
VERBOSE=yes

:Mirage
    PROTOCOL=limine
    KERNEL_PATH=boot:///boot/mirage-kernel
    CMDLINE=mirage.boot=limine log=serial
    RESOLUTION=1024x768x32
    KASLR=no
