TIMEOUT=0
GRAPHICS=yes
VERBOSE=yes

:Mirage Kernel
    PROTOCOL=limine
    KERNEL_PATH=boot:///boot/mirage-kernel.elf
    CMDLINE=mirage.boot=limine log=serial
    RESOLUTION=1024x768x32
    KASLR=no
