//! IOAPIC redirection support for legacy IRQ sources on real x86_64 hardware.
use core::sync::atomic::{AtomicBool, AtomicU64, Ordering}; use crate::arch::x86_64::acpi_madt::{MadtInfo,MadtInterruptOverride,MadtIoApic};
pub const IRQ_BASE_VECTOR:u8=0x20; pub const IRQ_TIMER_VECTOR:u8=IRQ_BASE_VECTOR; pub const IRQ_KEYBOARD_VECTOR:u8=IRQ_BASE_VECTOR+1;
const IOAPIC_REGSEL:usize=0x00; const IOAPIC_WINDOW:usize=0x10; const IOAPIC_REG_VERSION:u32=0x01; const IOAPIC_REDTBL_BASE:u32=0x10; const REDIR_MASKED:u64=1<<16; const REDIR_LEVEL:u64=1<<15; const REDIR_ACTIVE_LOW:u64=1<<13;
static IOAPIC_BASE_VIRT:AtomicU64=AtomicU64::new(0); static IOAPIC_GSI_BASE:AtomicU64=AtomicU64::new(0); static IOAPIC_READY:AtomicBool=AtomicBool::new(false);
#[derive(Clone,Copy,Debug,Eq,PartialEq)] pub enum IoApicStatus{Enabled{physical_base:u64,gsi_base:u32,max_redirection_entries:u8},Unavailable}
pub fn initialize_from_madt(madt:&MadtInfo,hhdm_offset:u64)->IoApicStatus{let Some(ioapic)=first_ioapic(madt) else{return IoApicStatus::Unavailable;}; IOAPIC_BASE_VIRT.store((ioapic.address as u64).saturating_add(hhdm_offset),Ordering::SeqCst); IOAPIC_GSI_BASE.store(ioapic.gsi_base as u64,Ordering::SeqCst); let max=max_redirection_entries(); mask_all(max); IOAPIC_READY.store(true,Ordering::SeqCst); route_legacy_irq(madt,0,IRQ_TIMER_VECTOR,false); route_legacy_irq(madt,1,IRQ_KEYBOARD_VECTOR,false); IoApicStatus::Enabled{physical_base:ioapic.address as u64,gsi_base:ioapic.gsi_base,max_redirection_entries:max}}
pub fn route_legacy_irq(madt:&MadtInfo,irq:u8,vector:u8,masked:bool){if !is_mmio_ready(){return;} let ov=madt.override_for_irq(irq).unwrap_or(MadtInterruptOverride{bus:0,source_irq:irq,gsi:irq as u32,flags:0}); let base=IOAPIC_GSI_BASE.load(Ordering::SeqCst) as u32; if ov.gsi<base{return;} let redir=ov.gsi-base; let mut entry=vector as u64; let polarity=ov.flags&0b11; let trigger=(ov.flags>>2)&0b11; if polarity==0b11{entry|=REDIR_ACTIVE_LOW;} if trigger==0b11{entry|=REDIR_LEVEL;} if masked{entry|=REDIR_MASKED;} write_redirection(redir,entry);}
fn first_ioapic(madt:&MadtInfo)->Option<MadtIoApic>{let mut i=0usize; while i<madt.io_apic_count(){if let Some(x)=madt.io_apics()[i]{return Some(x);} i+=1;} None} fn max_redirection_entries()->u8{if !is_mmio_ready(){return 0;} let v=unsafe{read(IOAPIC_REG_VERSION)}; (((v>>16)&0xff) as u8).saturating_add(1)} fn mask_all(entries:u8){let mut r=0u32; while r<entries as u32{write_redirection(r,REDIR_MASKED|IRQ_BASE_VECTOR as u64); r+=1;}} fn write_redirection(redir:u32,value:u64){let low=IOAPIC_REDTBL_BASE+redir*2; unsafe{write(low+1,(value>>32) as u32); write(low,value as u32);}} fn is_mmio_ready()->bool{IOAPIC_BASE_VIRT.load(Ordering::SeqCst)!=0} unsafe fn read(reg:u32)->u32{let base=IOAPIC_BASE_VIRT.load(Ordering::SeqCst); if base==0{return 0;} core::ptr::write_volatile((base as usize+IOAPIC_REGSEL) as *mut u32,reg); core::ptr::read_volatile((base as usize+IOAPIC_WINDOW) as *const u32)} unsafe fn write(reg:u32,value:u32){let base=IOAPIC_BASE_VIRT.load(Ordering::SeqCst); if base==0{return;} core::ptr::write_volatile((base as usize+IOAPIC_REGSEL) as *mut u32,reg); core::ptr::write_volatile((base as usize+IOAPIC_WINDOW) as *mut u32,value);}
